- service/diskoperation/filesystems/btrfs.cpp
- service/diskoperation/lvmoperator/lvmoperator.cpp
- service/diskoperation/partedcore.cpp
- service/diskoperation/partedcore.h
Description: 1.对于界面上被操作卸载的分区，下次刷新设备信息时。不挂载被卸载的分区
2.对于全盘加密安装的系统已经创建了pv，不需要再次创建。否则会出现创建pv失败
Log:
Bug: https://pms.uniontech.com/bug-view-149047.html
> fix: 全盘加密安装的系统，无法通过空间调整扩充空间

- service/diskoperation/partedcore.cpp
Description: lvm文件格式的支持中增加Btrfs、xfs、exfat文件系统的判断
Log: lvm文件格式的支持中增加Btrfs、xfs、exfat文件系统的判断
Bug: https://pms.uniontech.com/bug-view-151475.html
> fix: Btrfs,xfs,exfat的lvm分区擦除失败

- service/diskoperation/filesystems/btrfs.cpp
- service/diskoperation/filesystems/btrfs.h
- service/diskoperation/filesystems/exfat.cpp
- service/diskoperation/filesystems/exfat.h
- service/diskoperation/filesystems/xfs.cpp
- service/diskoperation/filesystems/xfs.h
Description: 空间调整失败的原因：1.btrfs支持增大与缩小、xfs只支持增大、exfat都不支持。界面没有对这三种情况进行区分并使用不同的文案提示
2.这三个文件系统的FS_Limits设置有误
Log: 临时先屏蔽掉这三个文件系统的扩容功能
Bug: https://pms.uniontech.com/bug-view-151491.html
> fix: btrfs,xfs,exfat格式分区空间调整功能失败

- service/diskoperation/partedcore.cpp
- service/diskoperation/partedcore.h
Description: 擦除分区后，界面上显示有挂载点。但是实际上该分区并未挂载
Log: 擦除分区时待分区被挂载后将分区从非挂载列表中删除。刷新设备信息时则不会umount该分区
Bug: https://pms.uniontech.com/bug-view-142257.html
> fix: 擦除分区，分区挂载点显示异常

- application/widgets/mountdialog.cpp
Description: exfat只能挂载非空目录
Log: 当挂载lvm里面的exfat到非空目录是弹窗报错
Bug: https://pms.uniontech.com/bug-view-152367.html
> fix: exfat的lvm挂载非空目录，没有提示，挂载不成功

- application/translations/deepin-diskmanager_az.ts
- application/translations/deepin-diskmanager_bo.ts
- application/translations/deepin-diskmanager_ca.ts
- application/translations/deepin-diskmanager_cs.ts
- application/translations/deepin-diskmanager_de.ts
- application/translations/deepin-diskmanager_en_US.ts
- application/translations/deepin-diskmanager_es.ts
- application/translations/deepin-diskmanager_fi.ts
- application/translations/deepin-diskmanager_fr.ts
- application/translations/deepin-diskmanager_hi_IN.ts
- application/translations/deepin-diskmanager_hu.ts
- application/translations/deepin-diskmanager_it.ts
- application/translations/deepin-diskmanager_ja.ts
- application/translations/deepin-diskmanager_ms.ts
- application/translations/deepin-diskmanager_nl.ts
- application/translations/deepin-diskmanager_pl.ts
- application/translations/deepin-diskmanager_pt.ts
- application/translations/deepin-diskmanager_pt_BR.ts
- application/translations/deepin-diskmanager_ru.ts
- application/translations/deepin-diskmanager_sl.ts
- application/translations/deepin-diskmanager_sq.ts
- application/translations/deepin-diskmanager_sr.ts
- application/translations/deepin-diskmanager_tr.ts
- application/translations/deepin-diskmanager_ug.ts
- application/translations/deepin-diskmanager_uk.ts
- application/translations/deepin-diskmanager_zh_CN.ts
- application/translations/deepin-diskmanager_zh_HK.ts
- application/translations/deepin-diskmanager_zh_TW.ts
- application/widgets/customcontrol/partitionwidget.cpp
Description: Click '+'修改为QString(tr("Click %")).arg("+")后翻译为更新
Log: 更新翻译文件
Bug: https://pms.uniontech.com/bug-view-152463.html
> fix: 全盘分区翻译异常

- application/widgets/customcontrol/partitionwidget.cpp
Description: 输入大小为空的情况onSetSliderValue直接返回了，导致m_currentEditSize错误
Log: 输入大小为空的情况视为0处理
Bug: https://pms.uniontech.com/bug-view-152433.html
> fix: 新建分区当大小处为空时，点击“+”号按钮，没有提示

- basestruct/utils.cpp
- basestruct/utils.h
- service/diskoperation/filesystems/ntfs.cpp
- service/diskoperation/partedcore.cpp
Description: 1.虽然执行了卸载操作但是再更新设备信息时又会重新挂载上。导致获取的FS_Limit错误
2.设备被挂载了，识别为分区正忙，执行了在线扩容的逻辑导致提示不支持
Log: 1.在计算FS_Limit时先卸载分区
2.resize时先卸载分区
3.判断设备是否busy，不使用设备信息中的值。而是重新根据是否被挂载来判断
> fix: 调整ntfs文件系统空间时提示不支持

- application/widgets/createlvwidget.cpp
- application/widgets/formatedialog.cpp
Description: 屏蔽lvm的中的磁盘加密功能，原因：功能不完善
Log:
Bug: https://pms.uniontech.com/bug-view-152927.html
> fix: 外接磁盘新建lvm加密分区，移除外接设备后，文管中仍然显示这些加密的Lvm分区

- application/translations/deepin-diskmanager_az.ts
- application/translations/deepin-diskmanager_ca.ts
- application/translations/deepin-diskmanager_de.ts
- application/translations/deepin-diskmanager_en_US.ts
- application/translations/deepin-diskmanager_fi.ts
- application/translations/deepin-diskmanager_hu.ts
- application/translations/deepin-diskmanager_nl.ts
- application/translations/deepin-diskmanager_pl.ts
- application/translations/deepin-diskmanager_sq.ts
- application/translations/deepin-diskmanager_uk.ts
- application/translations/deepin-diskmanager_zh_CN.ts
- application/translations/deepin-diskmanager_zh_HK.ts
- application/translations/deepin-diskmanager_zh_TW.ts
- application/widgets/mountdialog.cpp
- application/widgets/mountdialog.h
Description: 系统运行相关目录挂载的时候，目录文件被新设备里的内容替换。原有文件失效
Log: 只允许挂载/mnt和/media及其子目录。选择的挂载目录非上述目录则提示非法挂载点，且不能点击挂载按钮
Bug: https://pms.uniontech.com/bug-view-153001.html
> fix: 挂载点选择/bin/X11时，一直在挂载中，不能成功

- service/diskoperation/filesystems/ntfs.cpp
- service/diskoperation/partedcore.cpp
Description: getFileSystemLimits和resize方法中将ntfs格式umount了，umount的原因是解决分区被自动挂载导致功能命令执行失败的问题。
当前已恢复使用/usr/lib/udisks2/udisks2-inhibit拉起deepin-diskmanager-service，分区不会被自动挂载了。故删除umount
Log:
Bug: https://pms.uniontech.com/bug-view-154323.html
> fix: 新建ntfs格式的lvm分区，没有自动挂载，擦除后也不自动挂载

- application/widgets/createlvwidget.cpp
- application/widgets/customcontrol/partitionwidget.cpp
Description: 手动输入的分区大小不合法，分区合法大小的判断标准是>0 且<=剩余空间
Log: 创建lv和分区都增加的大小校验，如果大小设置不合法则不能点击“+”
> fix: 输入比剩余空间大的值，点击“+”号按钮，页面显示异常

- application/widgets/mountdialog.cpp
切换系统字号使用软件,页面内容出现重叠显示不全的问题
Log: 修复界面字号bug
Bug: https://pms.uniontech.com/bug-view-154475.html
> fix: 修复磁盘管理器字号20导致文案显示不全的问题-补充

- application/translations/deepin-diskmanager_cs.ts
- application/translations/deepin-diskmanager_en_US.ts
- application/translations/deepin-diskmanager_hu.ts
- application/translations/deepin-diskmanager_it.ts
- application/translations/deepin-diskmanager_pl.ts
- application/translations/deepin-diskmanager_uk.ts
- application/translations/deepin-diskmanager_zh_CN.ts
- application/translations/deepin-diskmanager_zh_HK.ts
- application/translations/deepin-diskmanager_zh_TW.ts
- application/widgets/diskinfodisplaydialog.cpp
- application/widgets/infoshowwidget.cpp
Description: 系统语言为中文时磁盘信息界面中的介质类型由SSD修改为固态，HDD修改为机械。其他语言保持不变
Log: 磁盘信息主页面以及磁盘右键->磁盘信息均修改
Bug: https://pms.uniontech.com/bug-view-155011.html
> fix: 修改磁盘信息介质类型文案

- application/partedproxy/dmdbushandler.cpp
- application/partedproxy/dmdbushandler.h
Description: 设备挂载信息未更新
Log: 获取设备后，查询/etc/mtab。 如果设备没有挂载，则将挂载点清空
Bug: https://pms.uniontech.com/bug-view-170853.html
> fix: 解决卸载U盘分区后，提示卸载成功依然显示已挂载

- application/partedproxy/dmdbushandler.cpp
Description: GPT磁盘获取的分区信息中设备节点名称为空，通过该设备节点查找挂载点信息出错，导致挂载信息未清除
Log: 使用设备名和分区编号组装设备节点名
> fix: GPT分区表中卸载分区，卸载成功，但是页面仍然显示有挂载点

- service/diskoperation/DeviceStorage.cpp
Description: UFS接口适配：
KLVV --->KelvinV   3.1
KLVU--->KelvinU    3.0 or 3.1
PGUV--->PanguV     3.0
PGUW-->PanuW       和主线一致
Log: 判断是否为华为适配，并通过设备型号填写接口类型
> fix: UFS接口适配

- application/partedproxy/dmdbushandler.cpp
从/etc/mtab读取信息判断未挂载条件错误
Log: 修复本机硬盘的分区挂载点显示为空，没有将挂载点正常显示出来
Bug: https://pms.uniontech.com/bug-view-183559.html
> fix: 修复本机硬盘的分区挂载点显示为空，没有将挂载点正常显示出来

- service/udev/deepin-diskmanager-authenticateProxy
Some mount points(-.mount var.mount) that some system services depend on are masked, which cause block services start. Sync the latest change from upstream and add "RequiredBy" exclude the system service depend on.
Log: Fix system service's moounts are masked.
> fix: Fix system services's mounts are masked

- service/diskoperation/luksoperator/luksoperator.cpp
The new cryptsetup version luksDump output json changed, it does not
include '\n' after json end. Parse this case in order to get correct luks info.
Log: Fix crypt format issue.
Bug: https://pms.uniontech.com/bug-view-182697.html
> fix: Fail to format with crypt on v23

- debian/changelog
- service/diskoperation/partedcore.cpp
- service/diskoperation/partedcore.h
Fix mount as root for FS: exfat fat32 ntfs.
Log: fix mount issue.
> fix: Fix mount as root for some FS

- application/main.cpp
- debian/changelog
When the disk manager starts, it will send an quit message to the background service, then start a new background service, and wait for the new background service to start before displaying the main interface.
In the extreme case, when the old service has not exited and the new service has not been started, the front end detects the existence of the service, then displays the main interface and sends a request to the old service. Since the old service may have exited during the execution of the request, the front end cannot receive the updateDeviceInfo signal and remains in the initialization interface.
The solution is that the front end needs to determine the PID of the service process when waiting for the new background service to start to ensure that the new service is running.
Log: …
> fix: Fix front-end startup stuck

- service/diskmanagerservice.cpp
- service/diskoperation/partedcore.cpp
- service/diskoperation/partedcore.h
When mounting ntfs, the mount option uid/gid is used, but diskmanager uses an empty string when mounting, causing the mount to fail. The solution is to pass in the user ID.
Log: fix mount ntfs fail
> fix: Fix mount ntfs fail

- service/udev/USBadd.sh
- service/udev/USBremove.sh
It needs to refresh USB devices info only for diskmanager, but the backend Dbus service may be actived.
Log: Fix USB devices are removed issue.
Bug: https://pms.uniontech.com/bug-view-244767.html
> fix: fix umount all USB devices at sometimes

- application/widgets/customcontrol/dmtreeviewdelegate.cpp
as title
Log: as title.
Bug: https://pms.uniontech.com/bug-view-247809.html
> fix: [247809/UI] item text color in dark mode.

- debian/changelog
- service/diskoperation/DeviceStorage.cpp
Adapt to new computer models PGUX-L5651.
Log: Fix disk interface display error on PGUX-L5651
Bug: https://pms.uniontech.com/bug-view-240983.html
> fix: Fix disk intreface display error on PGUX-L5651

- service/main.cpp
- service/watcher.cpp
- service/watcher.h
The watcher thread still running when want to exit the service app.
Log: Fix crash when exiting.
Bug: https://pms.uniontech.com/bug-view-248071.html
> fix: Fix crash when exiting

- debian/changelog
- service/diskoperation/DeviceStorage.cpp
Adapt to new computer models PGUX.
Log: Fix disk interface display error on PGUX
Bug: https://pms.uniontech.com/bug-view-240983.html
> fix: Fix disk intreface display error on PGUX

- service/diskoperation/DeviceStorage.cpp
make the hard disk serial number same as deepin-devicemanger
Log: adapt hard disk serial number
Bug: https://pms.uniontech.com/bug-view-251553.html
> fix: adapt hard disk serial number

- application/widgets/titlewidget.cpp
Description: It does not support format for all CD and DVD types. So, I have disabled the format option for these types.
Log: disable format for cd and dvd.
Bug: https://pms.uniontech.com/bug-view-253969.html
> fix: [dvd] disable format for cd and dvd

- service/diskoperation/DeviceStorage.cpp
The smartctl unsupport some USB type disk, it needs add -d option to get info, so set scsi as its default type.
Log: Fix incorrect media type for USB disk.
Bug: https://pms.uniontech.com/bug-view-264093.html
> fix: Fix incorrect media type for USB disk

- application/main.cpp
- basestruct/utils.cpp
- basestruct/utils.h
- debian/changelog
- service/PolicyKitHelper.cpp
- service/PolicyKitHelper.h
- service/diskmanagerservice.cpp
- service/diskmanagerservice.h
- service/diskoperation/filesystems/xfs.cpp
- service/diskoperation/luksoperator/luksoperator.cpp
- service/diskoperation/partedcore.cpp
- service/main.cpp
- service/policy/com.deepin.diskmanager.policy
- service/watcher.cpp
* add polkit support.
* fix command injection.
> feat: enhance dbus security

- service/diskoperation/partedcore.cpp
Diskmanager will modify fstab when mounting a disk, which may cause udisks to fail to mount the disk under certain conditions. Let’s not modify fstab anymore.
Log: Diskmanager no longer supports mounting disks at boot time
Bug: https://pms.uniontech.com/bug-view-286623.html
> fix: fix udisks fail to mount disk for invalid fstab

- application/partedproxy/dmdbushandler.cpp
- application/partedproxy/dmdbushandler.h
- application/partedproxy/dmdbusinterface.h
- debian/changelog
When deepin-diskmanager starts, it will start deepin-diskmanager-service first, and then obtain device information from deepin-diskmanager-service. If deepin-diskmanager-service takes too long to initialize due to the existence of external storage devices, deepin-diskmanager will fail to obtain device information. At this time, deepin-diskmanager-service has not registered the dbus service.
Let's re-initiate the request after failing to obtain device information.
Log: Fix get device info fail when init
Bug: https://pms.uniontech.com/bug-view-308533.html
> fix: Fix get device info fail when init
