linuxdeepin/deepin-diskmanager

basestruct/commondef.h
basestruct/deviceinfo.cpp
basestruct/deviceinfo.h
basestruct/luksenum.h
basestruct/luksstruct.cpp
basestruct/luksstruct.h
basestruct/lvmenum.h
basestruct/lvmstruct.cpp
basestruct/lvmstruct.h
basestruct/partitioninfo.h
service/diskmanagerservice.cpp
service/diskmanagerservice.h
service/diskoperation/luksoperator/luksoperator.cpp
service/diskoperation/lvmoperator/lvmoperator.cpp
service/diskoperation/partedcore.cpp
service/diskoperation/partedcore.h
service/diskoperation/sigtype.h
service/diskoperation/thread.cpp
service/diskoperation/thread.h

修复创建vg多一个扇区问题，添加luksmapper label属性
修复挂载后无法使用问题
整理代码风格
修复擦除逻辑
修复lvm作为系统盘bug
添加错误信号
Log: 修复创建vg多一个扇区问题，添加luksmapper label属性

fix: 修复创建vg多一个扇区问题，添加luksmapper label属性

---

basestruct/utils.cpp
basestruct/utils.h
service/diskoperation/filesystems/btrfs.cpp
service/diskoperation/filesystems/btrfs.h
service/diskoperation/partedcore.cpp
service/diskoperation/supportedfilesystems.cpp

Description: add btrfs filesystem support
Log: add btrfs filesystem support
Task: https://pms.uniontech.com/task-view-160451.html

feat: add btrfs filesystem support

---

debian/control
service/diskoperation/filesystems/exfat.cpp
service/diskoperation/filesystems/exfat.h
service/diskoperation/partedcore.cpp
service/diskoperation/supportedfilesystems.cpp

Description: add exfat filesystem support
Log: add exfat filesystem support
Task: https://pms.uniontech.com/task-view-160447.html

feat: add exfat filesystem support

---

service/diskoperation/filesystems/xfs.cpp
service/diskoperation/filesystems/xfs.h
service/diskoperation/partedcore.cpp
service/diskoperation/supportedfilesystems.cpp

Description: add xfs filesystem support
Log: add xfs filesystem support
Task: https://pms.uniontech.com/task-view-160449.html

feat: add xfs filesystem support

---

application/widgets/createlvwidget.cpp
application/widgets/mountdialog.cpp
application/widgets/mountdialog.h

Description: exfat文件系统挂载点必须为空目录，否则挂载失败
Log: 识别文件系统为exfat则校验挂载点是否为空，如果挂载点为空则弹窗提示更换挂载点
Bug: https://pms.uniontech.com/bug-view-151493.html

fix: 格式为exfat/exfat（AES加密）/exfat（SM4加密）的分区挂载失败

---

service/udev/99-diskmanager.rules
service/udev/USBadd.sh
service/udev/USBremove.sh

* feat: 优化USB热插拔刷新问题
非存储设备USB热插拔时，磁盘不做刷新
Log: 优化USB热插拔刷新问题

优化USB热插拔刷新问题 (#14)

---

application/translations/deepin-diskmanager_az.ts
application/translations/deepin-diskmanager_bo.ts
application/translations/deepin-diskmanager_ca.ts
application/translations/deepin-diskmanager_cs.ts
application/translations/deepin-diskmanager_de.ts
application/translations/deepin-diskmanager_en_US.ts
application/translations/deepin-diskmanager_es.ts
application/translations/deepin-diskmanager_fi.ts
application/translations/deepin-diskmanager_fr.ts
application/translations/deepin-diskmanager_hi_IN.ts
application/translations/deepin-diskmanager_hu.ts
application/translations/deepin-diskmanager_it.ts
application/translations/deepin-diskmanager_ja.ts
application/translations/deepin-diskmanager_nl.ts
application/translations/deepin-diskmanager_pl.ts
application/translations/deepin-diskmanager_pt.ts
application/translations/deepin-diskmanager_pt_BR.ts
application/translations/deepin-diskmanager_ru.ts
application/translations/deepin-diskmanager_sl.ts
application/translations/deepin-diskmanager_sq.ts
application/translations/deepin-diskmanager_sr.ts
application/translations/deepin-diskmanager_tr.ts
application/translations/deepin-diskmanager_ug.ts
application/translations/deepin-diskmanager_uk.ts
application/translations/deepin-diskmanager_zh_CN.ts
application/translations/deepin-diskmanager_zh_HK.ts
application/translations/deepin-diskmanager_zh_TW.ts
application/widgets/mountdialog.cpp

Description: 更新挂载点非法提示的翻译
Log:

feat: 更新挂载点非法提示的翻译

---

service/diskoperation/luksoperator/luksoperator.cpp

Description:  磁盘加密格式化增加错误日志
Log:

chore: 磁盘加密格式化增加错误日志

---

service/diskoperation/partedcore.cpp

Description: 原本的分区被加密后文件系统类型为crypto_LUKS, mkfs.exfat格式化该分区
时虽然没有报错但实际上分区格式还是crypto_LUKS，先将分区从crypto_LUKS
格式化为ext4，再将ext4格式化为exfat。 只有mkfs.exfat会有这种问题
Log:

fix: vg里面新建加密格式的lv，擦除为exfat格式时，擦除失败

---

service/udev/deepin-diskmanager-authenticateProxy

Description: 使用udisks2-inhibit导致文管隐藏系统磁盘信息
Log: 统一修改为简单启动deepin-diskmanager-service

fix: 选择挂载点处，点击打开文管，不显示系统盘，无法选择挂载点，只能手动输入

---

service/diskoperation/partedcore.cpp

Description: 擦除操作在格式化完成之后会进行挂载，由于probeDeviceInfo会触发udisk自动挂载。
导致本次擦除操作的挂载因为重复挂载而失败。
Log: 擦除操作挂载时，判断设备是否挂载。 如果已经挂载且挂载点与指定的挂载点一致则不重新挂载
如果挂载点不一致则先umount，在mount到指定挂载点

fix: 移动硬盘擦除失败

---

application/widgets/customcontrol/passwordinputdialog.cpp
application/widgets/customcontrol/passwordinputdialog.h
application/widgets/decryptdialog.cpp
application/widgets/decryptdialog.h
application/widgets/formatedialog.cpp
application/widgets/formatedialog.h

Description: 按照设计图修改
Log:
Bug: https://pms.uniontech.com/bug-view-153339.html

fix: 加解密弹窗的一级标题显示问题

---

application/widgets/customcontrol/partitionwidget.cpp
application/widgets/customcontrol/passwordinputdialog.cpp

【专业版】【1.3.18】【新建分区】 新建加密分区界面文案异常
Log: 【专业版】【1.3.18】【新建分区】 新建加密分区界面文案异常
Bug: https://pms.uniontech.com/bug-view-154065.html

fix: 【专业版】【1.3.18】【新建分区】 新建加密分区界面文案异常

---

service/udev/deepin-diskmanager-authenticateProxy

This reverts commit cdbbdb54f371b092fc27c66b6c78910b48976047.

Revert "fix: 选择挂载点处，点击打开文管，不显示系统盘，无法选择挂载点，只能手动输入 (#39)"

---

application/widgets/customcontrol/dmtreeview.cpp
application/widgets/customcontrol/dmtreeviewdelegate.cpp
application/widgets/customcontrol/partchartshowing.cpp
application/widgets/customcontrol/partitionwidget.cpp
application/widgets/decryptdialog.cpp
application/widgets/devicelistwidget.cpp
application/widgets/mountdialog.cpp
application/widgets/mountdialog.h

切换系统字号使用软件,页面内容出现重叠显示不全的问题
Log: 修复界面字号bug
Bug: https://pms.uniontech.com/bug-view-154475.html

fix: 修复磁盘管理器字号20导致文案显示不全的问题

---

.reuse/dep5
LICENSES/GPL-2.0-or-later.txt
README.md
README.zh_CN.md
application/partedproxy/dmdbusinterface.cpp
service/udev/deepin-diskmanager-authenticateProxy

Description: update readme and dep
Log: update readme and dep

chore: update readme and dep

---

service/diskoperation/partition.cpp

Description: 解决有符号整型溢出漏洞
Log:  解决有符号整型溢出漏洞
Task: https://pms.uniontech.com/task-view-197237.html

fix: 解决安全漏洞

---

service/diskoperation/partition.cpp

Description: 解决有符号整型溢出漏洞
Log: 解决有符号整型溢出漏洞

fix: 解决有符号整型溢出漏洞

---

service/diskoperation/DeviceStorage.cpp

Description: 增加ufs接口类型支持
Log: 增加ufs接口类型支持
Bug: https://pms.uniontech.com/bug-view-166277.html

fix: 修复存储设备接口类型与设备管理器不一致的问题

---

service/diskoperation/DeviceStorage.cpp

Description: 增加KLV L540 接口类型版本
Log: 增加KLV L540 接口类型版本

feat: 增加KLV L540支持

---

debian/changelog
service/diskoperation/DeviceStorage.cpp

Description: add W585 same as PGUV
Log: add W585 same as PGUV
Task: https://pms.uniontech.com/task-view-271675.html

chore: add W585

---

service/diskoperation/partedcore.cpp

When disk changing, it try to update the mount points for excluded devices. Incurrect parse fs part cause some system mount points are umounted. i.e. /recovery.
Log: fix umount issue.
Bug: https://pms.uniontech.com/bug-view-174395.html

fix: Some mountpoints are umounted.

---

application/translations/deepin-diskmanager_en_US.ts
application/widgets/customcontrol/dmtreeviewdelegate.cpp
application/widgets/customcontrol/infotopframe.cpp
application/widgets/devicelistwidget.cpp
application/widgets/diskbadsectorsdialog.cpp
application/widgets/diskhealthdetectiondelegate.cpp
application/widgets/diskhealthdetectiondialog.cpp
application/widgets/formatedialog.cpp
application/widgets/infoshowwidget.cpp
application/widgets/mainsplitter.cpp
application/widgets/mainwindow.cpp
application/widgets/mainwindow.h
application/widgets/titlewidget.cpp
application/widgets/titlewidget.h

Re-layout some UI components to solve UI adaptation problems.
Log: Fix some UI issues.
Bug: https://pms.uniontech.com/bug-view-204649.html
https://pms.uniontech.com/bug-view-203415.html
https://pms.uniontech.com/bug-view-135461.html
https://pms.uniontech.com/bug-view-135327.html
https://pms.uniontech.com/bug-view-158125.html
https://pms.uniontech.com/bug-view-158135.html
https://pms.uniontech.com/bug-view-158189.html

fix: Fix some UI issues

---

debian/changelog

New tag 1.3.29 release
Log: new tag 1.3.29

chore: new tag 1.3.29

---

service/diskoperation/DeviceStorage.cpp

1、在“smartctl”输出结果中增加“Model Number:”的判断
2、从smartctl以及lshw中均未获取到型号名时，将“UnKnow”设为型号名
3、处理for循环中重复声明了循环外已有的变量infoList导致的变量遮蔽问题

fix: 修复 “致钛PC005” 型号名未识别，并且显示为其他硬盘型号名的问题

---

debian/changelog

add new tag 1.3.30 for release.
Log: new release.

chore: new tag 1.3.30

---

application/widgets/customcontrol/dmframewidget.cpp
application/widgets/customcontrol/infotopframe.cpp
application/widgets/infoshowwidget.cpp

fix: UI error

---

debian/rules

disable diskmanager-daemon.service auto-start
Log: disable diskmanager-daemon.service auto-start
Bug: no

fix: disable diskmanager-daemon.service auto-start

---

debian/copyright

update the copyright to match the normal license
Log: update the copyright to match the normal license
Bug: no

doc: update the copyright to match the normal license

---

.reuse/dep5
service/diskoperation/blockspecial.cpp
service/diskoperation/blockspecial.h
service/diskoperation/filesystems/linuxswap.cpp
service/diskoperation/filesystems/linuxswap.h
service/diskoperation/supportedfilesystems.cpp
service/diskoperation/supportedfilesystems.h

As title.
Log: update copyright

doc: Update copyright

---

debian/changelog

new tag v1.3.36 for release.
Log: new tag v1.3.36

chore: [tag] new tag v1.3.36

---

application/widgets/customcontrol/partitionwidget.cpp

Force partition boundaries to be aligned to mebibyte.
Log: Fix create partition not aligned
Bug: https://pms.uniontech.com/bug-view-251763.html

fix: Fix create partition not aligned

---

service/diskoperation/DeviceStorage.cpp
service/diskoperation/DeviceStorage.h
service/diskoperation/partedcore.cpp

As title.
Log: Adapt disk firmware version
Bug: https://pms.uniontech.com/bug-view-251707.html

fix: Adapt disk firmware version

---

service/diskoperation/DeviceStorage.cpp

Adapt disk interface.
For display rules, see https://pms.uniontech.com/bug-view-251373.html
Log: Adapt disk interface
Bug: https://pms.uniontech.com/bug-view-257791.html

fix: Adapt disk interface

---

service/diskoperation/thread.cpp

It used the check size as block size into badblocks tool, which will report error on new e2fsprogs version.
Log: Fix block checking issue.
Bug: https://pms.uniontech.com/bug-view-252281.html

fix: Fix block checking issue

---

debian/changelog

v1.3.37 release.
Log: v1.3.37 release.

chore: [tag]v1.3.37

---

service/diskoperation/partedcore.cpp

Chear up some unused logs.
Log: Chear up some unused log

chore: Chear up some unused log

---

application/main.cpp
basestruct/utils.cpp
basestruct/utils.h
debian/changelog
service/PolicyKitHelper.cpp
service/PolicyKitHelper.h
service/diskmanagerservice.cpp
service/diskmanagerservice.h
service/diskoperation/DeviceStorage.cpp
service/diskoperation/filesystems/xfs.cpp
service/diskoperation/luksoperator/luksoperator.cpp
service/diskoperation/partedcore.cpp
service/main.cpp
service/policy/com.deepin.diskmanager.policy
service/watcher.cpp

After submitting the security hardening code, this caused other related applications to run abnormally, so let's roll back the related code.
Log: Rollback dbus security hardening code
Bug: https://pms.uniontech.com/bug-view-284953.html

chore: Rollback dbus security hardening code

---

debian/changelog

v1.4.1 release.
Log: v1.4.1 release.

chore: [tag]v1.4.1

---

service/diskoperation/partedcore.cpp

Diskmanager will modify fstab when mounting a disk, which may cause udisks to fail to mount the disk under certain conditions. Let’s not modify fstab anymore.
Log: Diskmanager no longer supports mounting disks at boot time
Bug: https://pms.uniontech.com/bug-view-286623.html

fix: fix udisks fail to mount disk for invalid fstab

---

application/translations/deepin-diskmanager_en_US.ts
application/widgets/diskhealthdetectiondialog.cpp
application/widgets/diskhealthdetectiondialog.h

Set color according system theme style.
Log: Fix theme style for health dialog
Bug: https://pms.uniontech.com/bug-view-275163.html

fix: Fix theme style for health dialog

---

debian/changelog

new tag v1.4.2
Log: v1.4.2 release.

chore: [tag]v1.4.2 release

---

debian/control

Remove exfat-fuse dependency.
Log: Remove exfat-fuse dependency

chore: Remove exfat-fuse dependency

---

service/diskoperation/supportedfilesystems.cpp

Remove support for FAT32 format.
Log: Fix fail to format disk to FAT32
Bug: https://pms.uniontech.com/bug-view-299499.html

fix: Fix fail to format disk to FAT32

---

service/configs/dbus/DiskManagerAdaptor.cpp
service/configs/dbus/DiskManagerAdaptor.h

Implement DiskManagerAdaptor class for DBus interface
Log: add DBus adaptor for disk manager service

feat: add DBus adaptor for disk manager service
